// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivcbtnacqixrlcngwesc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2Y2J0bmFjcWl4cmxjbmd3ZXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MDY3OTcsImV4cCI6MjA3NzI4Mjc5N30.gha1DcQAm9yrOeGiBrVnpNQifk5NLYDyst5ObvP2Fjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});